site_name: SPDX-lint
site_description: "Experimental SPDX baseline validator."

theme:
  name: 'material'
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  generator: false
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/spdx-lint
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/shage

copyright: Copyright &copy; 2022 Stefan Hagen under the MIT license

repo_name: ~sthagen/spdx-lint
repo_url: https://git.sr.ht/~sthagen/sixties
edit_uri: ""

plugins:
  - search
  - mkdocstrings

nav:
  - Introduction: 'index.md'
  - Install: 'install.md'
  - Usage: 'usage.md'
  - API: 'api.md'
  - Changes: 'changes.md'
  - Test Coverage: https://codes.dilettant.life/coverage/spdx-lint/
  - Third-Party: 'third-party/README.md'

markdown_extensions:
  - mkautodoc
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra_javascript:
